name: test environments
run-name: test-environments
on: [workflow_dispatch]
jobs:
  production-job:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo This is a var from an environment ${{ vars.NAME }}
