name: test environments
run-name: test-environments
on: [workflow_dispatch]
jobs:
  production-job:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo This is a var from production ${{ vars.NAME }}
  pages-job:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - run: echo This is a var from github pages ${{ vars.NAME }}
